#!/bin/bash                                                   
                                                                          
#OIFS="$IFS"                                                      
#IFS="${IFS}&"                                                    
#set $QUERY_STRING                                                
#Args="$*"                                                        
#IFS="$OIFS"                                                              
                                                                          
URL=${QUERY_STRING#*url=}                                                 
URL=${URL%%&*}                                                            
URL=${URL//+/ }                                                           
BOX=${QUERY_STRING#*box=}                                                 
BOX=${BOX%%&*}                                                            
BOX=${BOX//+/ }                                                           
                                                                          
function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }            
                                                                          
echo "Content-type: text/html;charset=UTF-8"                              
echo ""                                                                   
                                                                          
cat header.html                                                                

echo "<div>"
echo '<ul style="width:80%;">'

box=$(urldecode $BOX)
box=${box// /\.\*} 

#echo -e `/bin/grep -i -E $box /index.txt|sed 's/ /%20/g' |sed 's/^\.\///g'| sed "s/\(.*\)/<li><a href=$host\/&>&<\/a><br><\/li>/g"`
echo -e `/bin/grep -i $box /index.txt|sed 's/^\.\///g'|awk -v host=$host '{after=$0;before=$0;gsub(/ /,"%20",$after);print "<a href=/"$after">"before"</a><br></li><hr>"}'`

echo "</ul>"
echo "</div">
echo '</body>'
echo '</html>'
