#!/bin/sh
set -e

cd /tmp/

rm -f update.zip update.sql version.txt

[ -n "$UPDATE_URL" ] || UPDATE_URL=http://docker.xiaoya.pro

echo "Download $UPDATE_URL/update.zip"
wget -T 5 -q $UPDATE_URL/update.zip

if [ ! -f update.zip ]; then
        echo "Failed to download updated files, the upgrade process has aborted"
else
        unzip -o -q update.zip
	remote=$(head -n1 version.txt)
	if [ ! -f /opt/alist/data/version.txt ]; then
		echo 0.0.0 > /opt/alist/data/version.txt
	fi
	local=$(head -n1 /opt/alist/data/version.txt)
 	latest=$(printf "$remote\n$local\n" |sort -r |head -n1)	
	if [ $remote = $local ]; then
		echo `date` "current version is updated, no need to upgrade"
		exit
	elif [ $remote = $latest ]; then
		entries=$(expr `cat update.sql|wc -l` - 4)
		echo `date` "total" $entries "records"
        	sqlite3 /opt/alist/data/data.db <<EOF
drop table IF EXISTS x_storages;
.read update.sql
EOF
		echo `date` "update database succesfully, your new version is" $remote
		echo $remote > /opt/alist/data/version.txt
	else
		echo `date` "current version is updated, no need to downgrade"
		echo $remote > /opt/alist/data/version.txt
	fi
	rm -f update.zip update.sql version.txt
fi

exec "$@"
