name: build_docker

on:
  push:
    branches: [ main ]

jobs:
  build_docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: xhofe/alist
      - name: Replace release with dev
        run: |
          sed -i 's/release/dev/g' Dockerfile
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: xhofe
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

  build_docker_with_aria2:
    needs: build_docker
    name: Build docker with aria2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: alist-org/with_aria2
          ref: main
          persist-credentials: false
          fetch-depth: 0

      - name: Commit
        run: |
          git config --local user.email "i@nn.ci"
          git config --local user.name "Noah Hsu"
          git commit --allow-empty -m "Trigger build for ${{ github.sha }}"

      - name: Push commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          branch: main
          repository: alist-org/with_aria2