name: release_linux_musl_arm

on:
  release:
    types: [ published ]

jobs:
  release_arm:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ '1.20' ]
    name: Release
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        run: |
          bash build.sh release linux_musl_arm

      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          files: build/compress/*
